#Local Development
version: '3.8'

services:
  ms-search-food:
    build:
      context: ./ms-search-food
      dockerfile: Dockerfile
    volumes:
      - /tmp
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
    env_file:
      - path: .env
    ports:
      - "8080:8080"
    networks:
      - ms-search-food-network

networks:
  ms-search-food-network:
    driver: bridge
