version: '3.9'

services:
  ms-search-food:
    build:
      context: ./ms-search-food
      dockerfile: Dockerfile
    volumes:
      - /tmp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json
    ports:
      - "8080:8080"
    networks:
      - ms-search-food-network

networks:
  ms-search-food-network:
    driver: bridge
