#GitHub Deploiment
name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: path/to/Dockerfile  # Adjust the path if Dockerfile is not in the root
          push: true
          tags: your-dockerhub-username/your-image-name:latest

      - name: Run Docker container
        run: |
          docker run -d --name ms-search-food-container \
            -e SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} \
            -p 8080:8080 \
            your-dockerhub-username/your-image-name:latest
